search_task:
  description: >
    Search for the latest news articles and trends about {topic}.
  expected_output: >
    A list of relevant and popular recent articles about the trend.
  agent: search_agent

analysis_task:
  description: >
    Analyze the retrieved articles for trend relevance and popularity.
  expected_output: >
    Ranked list of articles with relevance scores.
  agent: analysis_agent

report_task:
  description: >
    Create a summarized trend report based on the analyzed articles.
  expected_output: >
    A final concise trend report.
  agent: report_agent
