search_task:
  description: >
    Search for the latest and most relevant articles about the topic: {topic}. 
    Use reputable sources such as news outlets, industry blogs, and trend analysis platforms. 
    Extract meaningful content — not just links — including key quotes or summaries.
  expected_output: >
    A curated list of the top 2 specific and up-to-date *articles* related to {topic}, each including:
    - Article title
    - Source name
    - Publication date
    - Direct link to the article page (not homepage)
    - 3 sentence summary of the article content
  agent: search_agent

analysis_task:
  description: >
    Given a list of articles on a topic, the agent must analyze **each article** and rank them in order of relevance to the original search topic.
    For each article, the agent should provide:
      - Title
      - A short summary explaining why the article is relevant to the search topic

    The output should be a **ranked list** (starting from most to least relevant), with **both articles analyzed thoroughly**.
    Do not skip any article. Assume the list always includes exactly 2 articles.
    The analysis should be objective and based on content relevance.
  expected_output: >
    A ranked list of the top 2 articles, each with a short summary
  agent: analysis_agent

report_task:
  description: >
    Using the results from the analysis task, write a structured and concise report summarizing the top trends related to {topic}.
  expected_output: >
    A structured trend report highlighting the key findings, written in markdown format.
  agent: report_agent
